name: Accessibility
on:
  push:
jobs:
  accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: pip install Django
      - run: django-admin startproject allyapp
      - run: python allyapp/manage.py migrate
      - run: python allyapp/manage.py runserver 0:8000 &
      - run: curl http://127.0.0.1:8000/
      - run: npm install -g http-server@14
      - run: wget --no-host-directories -P ./pages --mirror http://127.0.0.1:8000/
      - run: wget --no-host-directories -P ./pages --mirror http://127.0.0.1:8000/admin/
      - run: http-server ./pages --port 4000 &
      - run: npm install -g pa11y-ci
      - run: pa11y-ci --config pa11y.static.config.js
      - run: cat pa11y.json
      - run: pa11y-ci --threshold 1
